Lang German added
skybrud/Skybrud.Umbraco.Redirects pull request #165
Opened 2023-01-25 14:18 UTC by Laurin-migi

I come from Switzerland and have therefore added a German language to your great package.

2023-02-01 20:29 UTC, abjerner commented
Thanks a lot @Laurin-migi 👍 

Any reason why this PR is targeting **v2/main** (Umbraco 8) and not **v4/main** (Umbraco 10+)?

2023-02-02 08:21 UTC, Laurin-migi commented
> Any reason why this PR is targeting v2/main (Umbraco 8) and not v4/main (Umbraco 10+)?
yes, thats because we use umbraco v8 and we will use umvraco 10 later. When I have time, I will make a new PR with v10

2023-02-14 18:11 UTC, abjerner requested changes
Hi @Laurin-migi 

I've found a minor issue. Even for the German translation, this is supposed to be the English word `Content`, right?

If you can look into this, I'd be happy to merge, and then push a new release for Umbraco 8 😉

2023-02-14 18:11 UTC, abjerner commented on src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Lang/de.xml
> +    <key alias="content">Contet</key>
Shouldn't this be `Content` like line 40?

2025-01-27 18:37 UTC, closed without merging