Updated RedirectsMiddleware 404 detection logic to use Response.OnStarting
skybrud/Skybrud.Umbraco.Redirects pull request #97
Opened 2021-08-16 09:00 UTC by vsilvar

This will allow redirects to still work even if a ContentFinder is used to display custom 404 pages for example.

It also makes the code a bit more straightforward and brings it more in line with the v8 version of the package.

2021-08-16 15:36 UTC, abjerner requested changes
Hi @vsilvar 

Thanks for creating this PR 👍

Can you help me out by sharing some reproduceable examples on when it doesn't work, and when it works?

2021-08-16 16:07 UTC, lauraneto commented
Hi @abjerner ,

Here is an example of an `IContentLastChanceFinder` which will set a custom 404 page.
```
public class LastChanceContentFinder : IContentLastChanceFinder
{
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public LastChanceContentFinder(IUmbracoContextAccessor umbracoContextAccessor)
    {
        _umbracoContextAccessor = umbracoContextAccessor;
    }

    public bool TryFindContent(IPublishedRequestBuilder request)
    {
        IPublishedContent? errorPage = _umbracoContextAccessor.UmbracoContext.Content.GetAtRoot().FirstOrDefault();

        request
            .SetPublishedContent(errorPage)
            .SetResponseStatus(404)
            .SetNoCacheHeader(true);

        return errorPage != null;
    }
}
```
Then I register it in `Startup.cs`
```
umbracoBuilder.SetContentLastChanceFinder<LastChanceContentFinder>();
```

With the existing logic, since I am setting the published content to my custom 404 page, `publishedRequest is not null && publishedRequest.HasPublishedContent()` will return true, so the logic to check for redirects will not be called.

That makes it so that if I create a redirect from a non existing url, and try to access it, I will just see my 404 page, instead of being redirected.

The proposed pull request fixes the issue entirely.

I hope this answers your question!

2021-08-16 16:15 UTC, vsilvar commented
@abjerner We also found some small issues:
- Umbraco will not load with the NuGet installed and without `JetBrains.Annotations`, as it's doing reflection and it fails to find the referenced assembly (Might be worth to either make it an explicit dependency or update `Skybrud.Essentials`)
- `App_Plugin` files don't seem to work unless copied manually to project as the contentFiles don't seem to be automatically copied

Not sure if you want us to create issues for it, as the v9 version isn't even released yet 😅

2021-08-17 07:29 UTC, abjerner commented
Thanks @lauraneto and @vsilvar 

I'll try finding some time to have a look at this 😉 

For the JetBrains issue, it's Umbraco's type finder that looks a bit too broadly. I did create an [issue](https://github.com/umbraco/Umbraco-CMS/issues/10801) and subsequent [PR](https://github.com/umbraco/Umbraco-CMS/pull/10808). It should be part of 9.0.0-rc002 whenever that it out. Until then, the issue can be solved by installing JetBrains.Annotations manually.

Regarding the "client" files of the package, that is something that should be addressed once I push a pre release to NuGet (which I hopefully will be able to do soon). With the current state of the package, you'll have to clone the repo, and then copy the files manually to your solution.

2021-09-07 13:02 UTC, PhyxionNL commented
This is also necessary if you use U9's Error404Collection.

2021-10-11 13:32 UTC, JFSeibert commented
any chance this gets accepted?
would definitely fix my issue as well
c.f. https://our.umbraco.com/forum/umbraco-9/107293-skybrud-redirects-does-not-redirect-when-error404collection-is-set-up

2021-11-18 19:57 UTC, merged

2021-11-18 20:00 UTC, abjerner commented
Thanks a lot @vsilvar 👍 

While this didn't take long to merge and test, I haven't been able to find the time and energy to look at this until now.

The changes will be part of `3.0.0-alpha006`, which I hope to push tonight 😉